# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            NoPressuRe
tagline:          'blog'
description:      'NoPressuRe blog.'
url:              http://www.nopressure.co.uk/blog
baseurl:
commentsystem:    google
disqus:           example

author:
  name:           NoPressuRe
  url:            https://hiromipaw.github.io

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:
  - icon:         twitter
    url:          https://twitter.com/nopressure
    desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/nopressurelabs
    desc:         Fork me on github

  - icon:         tumblr
    url:          https://blog.nopressure.co.uk
    desc:         Follow me on tumblr

  - icon:         feed
    url:          http://www.nopressure.co.uk/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         NoPressuRe
  url:            http://www.nopressure.co.uk
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
